apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sentinelforge-demo
  namespace: default
  labels:
    app: sentinelforge-demo
spec:
  replicas: 2
  progressDeadlineSeconds: 60
  progressDeadlineAbort: true

  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: {}

  selector:
    matchLabels:
      app: sentinelforge-demo

  template:
    metadata:
      labels:
        app: sentinelforge-demo
    spec:
      containers:
        - name: app
          image: 216453078762.dkr.ecr.ap-south-1.amazonaws.com/sentinelforge-demo:4fc0034eccf2fd076a48bbe756ce10c45426d3af
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi

---
apiVersion: v1
kind: Service
metadata:
  name: sentinelforge-demo
spec:
  selector:
    app: sentinelforge-demo
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
