name: SentinelForge CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Validate GitOps manifests
        run: |
          kubectl kustomize platform/gitops/apps/sentinelforge-demo > /tmp/rendered.yaml
          test -s /tmp/rendered.yaml

      - name: Show rendered manifests
        run: |
          cat /tmp/rendered.yaml

  secret-scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  container-security:
    name: Build and Scan Container
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t sentinelforge-demo:${{ github.sha }} \
            ./apps/sentinelforge-demo

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sentinelforge-demo:${{ github.sha }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Tag image for Amazon ECR
        run: |
          docker tag sentinelforge-demo:${{ github.sha }} \
            ${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}

      - name: Push image to Amazon ECR
        run: |
          docker push \
            ${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}

      - name: Update GitOps image
        run: |
          sed -i "s|image: .*|image: ${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}|" \
          platform/gitops/apps/sentinelforge-demo/deployment.yaml

      - name: Commit GitOps update
        run: |
           git config user.name "github-actions[bot]"
           git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

           git add platform/gitops/apps/sentinelforge-demo/deployment.yaml

           git commit -m "ci: update demo image to ${{ github.sha }}" || exit 0
           git push